version: '2'
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    image: brramos/docker-angular
    ports:
      - "3000:3000"
    volumes:
      - ./index.js:/usr/src/app/index.js
      - ./app:/usr/src/app/app
