version: '1'
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    image: brramos/docker-angular
    ports:
      - "8000:8000"
    volumes:
      - ./index.js:/usr/src/app/index.js
      - ./app:/usr/src/app/app
