version: '2'
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    image: brramos/docker-angular
    ports:
      - "3001:3001"
    volumes:
      - ./app/index.js:/var/www/app/index.js
      - ./app:/var/www/app
      - ./dist:/var/www/dist
